### PR TITLE
Feature/contact newsletter form

### PR DESCRIPTION
**Pull request by Thida612**
I added html and java script contact and newsletter form to be added to the website.

### CODE REVIEW

**Comment by CMakousky** [comment]
Which files contain the contact and newsletter features? There appear to be several extra files generated by bootstrap studio here.

**Comment by Thida612** [comment]
Do you see contact2 file? with the code.

<!DOCTYPE html>
<html data-bs-theme="light" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0,
shrink-to-fit=no">
  <title>Home - Brand</title>
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="
https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800
&amp;display=swap">
  <link rel="stylesheet" href="
https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity=
"sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk"
crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-md sticky-top py-3 navbar-dark" id=
"mainNav">
    <div class="container">
      <a class="navbar-brand d-flex align-items-center" href="/">Brand</a>
      <button data-bs-toggle="collapse" class="navbar-toggler"
data-bs-target="#navcol-1">
        <span class="visually-hidden">Toggle navigation</span><span class=
"navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navcol-1"></div>
    </div>
  </nav>



  <section class="py-5 bg-dark">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-8 col-xl-6 text-center mx-auto">
          <h2 class="fw-bold text-white">Contact Us</h2>
        </div>
      </div>
      <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-xl-4">
          <div>
            <form class="p-3 p-xl-4" method="post">
              <div class="name mb-3">

                <input class="form-control" type="text" id="name" name=
"name" placeholder="Name">
              </div>
              <div class="email mb-3">

                <input class="form-control" type="email" id="email" name=
"email" placeholder="Email">
              </div>
              <div class="mb-3 message-box">
                <textarea class="form-control" id="msg" name="message" rows=
"6" placeholder="Message"></textarea>
              </div>
              <div>
                <button class="btn btn-primary shadow d-block w-100" type=
"button" id="send" onclick="sendMessage()">Send</button>
              </div>
              <div class="message">
                <div class="alert alert-success mt-2" id="success" style="
display:none;">Your Message Successfully Sent!</div>
                <div class="alert alert-danger mt-2" id="danger" style="
display:none;">Fields can't be empty!</div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  
  <section class="py-5">
    <div class="container">
      <div class="bg-dark border rounded border-dark d-flex flex-column
justify-content-between align-items-center flex-lg-row p-4 p-lg-5">
        <div class="text-center text-lg-start py-3 py-lg-1">
          <h2 class="fw-bold mb-2">Subscribe to our newsletter</h2>
        </div>
        <form class="d-flex justify-content-center flex-wrap flex-lg-nowrap"
method="post">
          <div class="my-2">
            <input class="border rounded-pill shadow-sm form-control" type=
"email" id="newsletter-email" name="email" placeholder="Your Email">
          </div>
          <div class="my-2">
            <button class="btn btn-primary shadow ms-2" type="button" id=
"subscribe" onclick="validateNewsletter()">Subscribe</button>
          </div>
          <div class="message">
            <div class="alert alert-success mt-2" id="newsletter-success"
style="display:none;">Thank you for subscribing!</div>
            <div class="alert alert-danger mt-2" id="newsletter-danger"
style="display:none;">Email can't be empty!</div>
          </div>
        </form>
      </div>
    </div>
  </section>

  
  <script>
    function sendMessage(){
      var Name = document.getElementById('name');
      var email = document.getElementById('email');
      var msg = document.getElementById('msg');
      const success = document.getElementById('success');
      const danger = document.getElementById('danger');

      if(Name.value === '' || email.value === '' || msg.value === ''){
          danger.style.display = 'block';
      } else {
          setTimeout(() => {
              Name.value = '';
              email.value = '';
              msg.value = '';
          }, 2000);

          success.style.display = 'block';
      }

      setTimeout(() => {
          danger.style.display = 'none';
          success.style.display = 'none';
      }, 4000);
    }

    function validateNewsletter(){
      var newsletterEmail = document.getElementById('newsletter-email');
      const newsletterSuccess = document.getElementById('newsletter-success'
);
      const newsletterDanger = document.getElementById('newsletter-danger');

      if(newsletterEmail.value === ''){
          newsletterDanger.style.display = 'block';
      } else {
          setTimeout(() => {
              newsletterEmail.value = '';
          }, 2000);

          newsletterSuccess.style.display = 'block';
      }

      setTimeout(() => {
          newsletterDanger.style.display = 'none';
          newsletterSuccess.style.display = 'none';
      }, 4000);
    }
  </script>

  <script src="assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/js/script.min.js"></script>
</body>
</html>

**Comment by Thida612** [comment]
You might be able to copy and paste this since your just adding our codes
to your html file.
<section class="py-5 bg-dark">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-8 col-xl-6 text-center mx-auto">
          <h2 class="fw-bold text-white">Contact Us</h2>
        </div>
      </div>
      <div class="row d-flex justify-content-center">
        <div class="col-md-6 col-xl-4">
          <div>
            <form class="p-3 p-xl-4" method="post">
              <div class="name mb-3">

                <input class="form-control" type="text" id="name" name=
"name" placeholder="Name">
              </div>
              <div class="email mb-3">

                <input class="form-control" type="email" id="email" name=
"email" placeholder="Email">
              </div>
              <div class="mb-3 message-box">
                <textarea class="form-control" id="msg" name="message" rows=
"6" placeholder="Message"></textarea>
              </div>
              <div>
                <button class="btn btn-primary shadow d-block w-100" type=
"button" id="send" onclick="sendMessage()">Send</button>
              </div>
              <div class="message">
                <div class="alert alert-success mt-2" id="success" style="
display:none;">Your Message Successfully Sent!</div>
                <div class="alert alert-danger mt-2" id="danger" style="
display:none;">Fields can't be empty!</div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  
  <section class="py-5">
    <div class="container">
      <div class="bg-dark border rounded border-dark d-flex flex-column
justify-content-between align-items-center flex-lg-row p-4 p-lg-5">
        <div class="text-center text-lg-start py-3 py-lg-1">
          <h2 class="fw-bold mb-2">Subscribe to our newsletter</h2>
        </div>
        <form class="d-flex justify-content-center flex-wrap flex-lg-nowrap"
method="post">
          <div class="my-2">
            <input class="border rounded-pill shadow-sm form-control" type=
"email" id="newsletter-email" name="email" placeholder="Your Email">
          </div>
          <div class="my-2">
            <button class="btn btn-primary shadow ms-2" type="button" id=
"subscribe" onclick="validateNewsletter()">Subscribe</button>
          </div>
          <div class="message">
            <div class="alert alert-success mt-2" id="newsletter-success"
style="display:none;">Thank you for subscribing!</div>
            <div class="alert alert-danger mt-2" id="newsletter-danger"
style="display:none;">Email can't be empty!</div>
          </div>
        </form>
      </div>
    </div>
  </section>

  
  <script>
    function sendMessage(){
      var Name = document.getElementById('name');
      var email = document.getElementById('email');
      var msg = document.getElementById('msg');
      const success = document.getElementById('success');
      const danger = document.getElementById('danger');

      if(Name.value === '' || email.value === '' || msg.value === ''){
          danger.style.display = 'block';
      } else {
          setTimeout(() => {
              Name.value = '';
              email.value = '';
              msg.value = '';
          }, 2000);

          success.style.display = 'block';
      }

      setTimeout(() => {
          danger.style.display = 'none';
          success.style.display = 'none';
      }, 4000);
    }

    function validateNewsletter(){
      var newsletterEmail = document.getElementById('newsletter-email');
      const newsletterSuccess = document.getElementById('newsletter-success'
);
      const newsletterDanger = document.getElementById('newsletter-danger');

      if(newsletterEmail.value === ''){
          newsletterDanger.style.display = 'block';
      } else {
          setTimeout(() => {
              newsletterEmail.value = '';
          }, 2000);

          newsletterSuccess.style.display = 'block';
      }

      setTimeout(() => {
          newsletterDanger.style.display = 'none';
          newsletterSuccess.style.display = 'none';
      }, 4000);
    }
  </script>

  <script src="assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/js/script.min.js"></script>
</body>
</html>
ReplyForward
Add reaction

**Comment by CMakousky** [comment]
Can the extra junk get removed feature branch? The project is at a state where I would prefer use gitHub to do the merge, also I think we need to master this process for the future projects. I want to be able to approve a merge into the main branch, but I don't want to add the extra junk to the main branch.

**Comment by Thida612** [comment]
Can I send it like how I been sending ? or do you just want me to send the
code for the contact and newsletter form html javascript??

**Comment by Thida612** [comment]
I created a new branch called feature/contact-newsletter and pushed it
hopefully this works!

**Comment by Thida612** [comment]
Hi! question for you. I was thinking of our presentation slide. Do you
think we should add bullet points with a little detail for each section? So
when people see it, it doesn't look plain?

**Pull request closed without merging**
